language: generic
sudo: required
services:
- docker

env:
  global:
  - IMG_NAME="docker.io/mattsch/rpi-nginx-extra"

script:
- 'docker login -u "$D_U" -p "$D_P"'
- 'docker build -t ${IMG_NAME}:${TRAVIS_BUILD_NUMBER} -t ${IMG_NAME}:latest .'
- 'docker push ${IMG_NAME}:${TRAVIS_BUILD_NUMBER}'
- 'docker push ${IMG_NAME}:latest'

if: branch = master
